---
version: '3.9'

services:
  nginx:
    image: nginx:1.22.0
    hostname: nginx
    restart: unless-stopped
    ports:
      - "172.18.0.95:80:80"
      - "172.18.0.95:443:443"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/ssl.d:/etc/nginx/ssl.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./data:/data

networks:
  default:
    external: true
    name: nginx_proxy
